---
- hosts: masters
  gather_facts: true
  become: true
  roles:
  - { role: prepare, tags: prepare }
  - { role: etcd, tags: etcd }
  - { role: keepalived, tags: keepalived }
  - { role: master, tags: master }

